### ISSUE TITLE
Add to help text

### ISSUE THREAD

**Issue by KatherineBliss** [nhsconnect/gpconnect-appointment-checker#101]
In the section of Help text 'I can't see any appointments, what's wrong?'

Add another bullet point to the end of the list as follows:

**- The practice has made slots available to GP Connect but they are under embargo**

**Comment by jonnyry** [comment]
@ChristopherJamesMorris This isn't in the master branch?

Also the checkin contains work other than this change https://github.com/nhsconnect/gpconnect-appointment-checker/commit/5a2621b15c1bec1f44642a99ffec7440ed2a5a39

**Comment by jonnyry** [comment]
Fixed
