### ISSUE TITLE
Provide ability to include free slots in the past

### ISSUE THREAD

**Issue by ChristopherJamesMorris** [nhsconnect/gpconnect-appointment-checker#103]
Depending on the provider of the free appointment slots, there are some scenarios where appointments from the past are included.

As such, there needs to be ability to filter whether or not these are displayed.

**Comment by jonnyry** [comment]
@ChristopherJamesMorris could you migrate to develop branch?

**Comment by ChristopherJamesMorris** [comment]
This is now implemented.
