### ISSUE TITLE
Slot auditing raises exception in certain situations

### ISSUE THREAD

**Issue by ChristopherJamesMorris** [nhsconnect/gpconnect-appointment-checker#115]

**Comment by jonnyry** [comment]
@ChristopherJamesMorris Could you explain the scenario in which this issue occurred so I can retest?

**Comment by ChristopherJamesMorris** [comment]
@jonnyry Yes, if the slot search generates an issue from the provider, vis-a-vis the slot search has an Issue element in the Bundle Json

**Comment by jonnyry** [comment]
@ChristopherJamesMorris  Could you point me to an example piece of JSON (perhaps from one of the test environments) that I would need to recreate this?  Thanks
