### ISSUE TITLE
Provide application monitoring/reporting function for admins

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-appointment-checker#121]
As part of our non functional / monitoring requirements, create ability for a non-technical user to monitor/report on the checker's usage.

As a first draft (in order to meet our FRA obligations) four SQL functions were created in #137   that create summary statistics from the audit and logging data the application produces:

- `reporting.get_user_stats()`
- `reporting.get_search_stats()`
- `reporting.get_transaction_stats()`
- `reporting.get_errors_last_month()`

Suggest that we evolve this so that, admin users of the application can see these on a 'reporting' page.

Also some indexes are required to speed up / reduce DB load for the above functions.

**Comment by ChristopherJamesMorris** [comment]
This is now implemented.
