### ISSUE TITLE
Allow searches on multiple ODS codes

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-appointment-checker#125]

**Comment by jonnyry** [comment]
eea920a5b0ae977da79943506764bd9a48290d07
3c6fb251b901fb41c1ac663e103b6b2bf59da5b1
248178db4baa0cf47bcaddad74056ce46c0d90b4

**Comment by ChristopherJamesMorris** [comment]
Multiple ODS code search has been implemented.
