### ISSUE TITLE
Prevent ALB health check from filling up the logging.web_request

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-appointment-checker#131]

**Comment by jonnyry** [comment]
Consider:
- making the UserAgent and URL values configuration
- migrating the health check onto its own URL

**Comment by jonnyry** [comment]
Created ticket #132 to consider follow ups to the change.

**Comment by jonnyry** [comment]
@ChristopherJamesMorris Was this meant to be removed?

`if ((webRequest.UserAgent == "ELB-HealthChecker/2.0") && (webRequest.Url == "/"))
                 return;`

**Comment by ChristopherJamesMorris** [comment]
Yes, as the healthcheck is now available via the built in .net5 healthchecker

**Comment by jonnyry** [comment]
Ah.. the logging.web_request table is filling up again now i've switched the healthcheck over to /Healthcheck.

**Comment by ChristopherJamesMorris** [comment]
Ok, I'll take a look
