### ISSUE TITLE
Page menu bar is unavailable at narrower widths

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-appointment-checker#139]
The page menu disappears at narrower widths, but isn't replaced with a menu button:

<img width="970" alt="Screenshot 2021-03-19 at 10 06 37" src="https://user-images.githubusercontent.com/7916532/111764350-04fe1180-889b-11eb-9763-4f395732da2f.png">

NHS.UK website at a narrower width:

<img width="970" alt="Screenshot 2021-03-19 at 10 07 00" src="https://user-images.githubusercontent.com/7916532/111764540-35de4680-889b-11eb-9c4c-2c314892bcb7.png">

**Comment by ChristopherJamesMorris** [comment]
Checked and verified as working in the DEV environment.

When the browser window is shrunk, a Menu button is shown which when clicked exposes an accessible menu with all the available menu options.

**Comment by jonnyry** [comment]
Fixed

**Comment by ChristopherJamesMorris** [comment]
This has now been released to LIVE.
