### ISSUE TITLE
Highlight consumer if organisation is not enabled for GPC

### ISSUE THREAD

**Issue by ChristopherJamesMorris** [nhsconnect/gpconnect-appointment-checker#143]

**Comment by ChristopherJamesMorris** [comment]
This is now implemented.

**Comment by jonnyry** [comment]
Query needs to be against nhsAs object rather than nhsMhs object - consumer systems are not usually configured the same as provider systems, and don't tend to have interaction IDs on the nhsMhs object.

**Comment by jonnyry** [comment]
(&(nhsIDCode=CONSUMER_ODS_CODE)(objectClass=nhsAs)(nhsAsSvcIA=urn:nhs:names:services:gpconnect:fhir:rest:read:metadata-1)) [uniqueIdentifier]

If this returns one of more results the consumer organisation is enabled for GP Connect, otherwise it is not.

**Comment by ChristopherJamesMorris** [comment]
Now implemented.
