### ISSUE TITLE
Email changes

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-appointment-checker#145]
Modify the email sent to users:

- don't bcc the email to the appointment checker mailbox (it's already in the sent folder)
- Change "...appears on the Checker Tool pages" to "...appears on the **Appointment** Checker Tool pages"
- Email titles:
  - "GP Connect Appointment Checker - User account created"
  - "GP Connect Appointment Checker - Account deactivated"

**Comment by ChristopherJamesMorris** [comment]
This is now implemented.
