### ISSUE TITLE
Sign in and Create Account buttons should be styled to required standards.

### ISSUE THREAD

**Issue by ChristopherJamesMorris** [nhsconnect/gpconnect-appointment-checker#168]

**Comment by jonnyry** [comment]
Suggest something like this, reducing the relative prominence of "register":

<img width="1241" alt="Login page" src="https://user-images.githubusercontent.com/7916532/125053360-eb2c4880-e09c-11eb-960e-94dda64f3782.png">

**Comment by ChristopherJamesMorris** [comment]
Changes have now been implemented.

**Comment by ChristopherJamesMorris** [comment]
Closing as changes now implemented.
