### ISSUE TITLE
Blank user registration screen

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-appointment-checker#170]
Sometimes getting a blank user screen...possibly after leaving the screen in the browser for a while (15 mins?)...

<img width="1175" alt="Screenshot 2021-07-09 at 11 46 58" src="https://user-images.githubusercontent.com/7916532/125066864-6694f680-e0ab-11eb-8935-d2e8161d08ab.png">

**Comment by ChristopherJamesMorris** [comment]
Fix has now been implemented.

**Comment by ChristopherJamesMorris** [comment]
Closing as now fixed
