### ISSUE TITLE
Application.user authorised_date is being updated in some instances incorrectly

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-appointment-checker#187]
On friday I authorised five users (using the UI) - (see sent emails to determine the users).

However 14 records have had their authorised date updated:

`select * from application."user" where date(authorised_date) = '2021-07-23'`

also see:

`select * from audit.entry where entry_type_id = 10;`

Is the UI re-submitting all of the records in the current view, regardless of whether they've changed?

**Comment by ChristopherJamesMorris** [comment]
This is now fixed with an update to a db function for updating user statuses

**Comment by jonnyry** [comment]
Fixed.
