### ISSUE TITLE
Make "consumer ODS code not enabled for GP Connect" warning in multi search more prominent

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-appointment-checker#192]
<img width="1057" alt="Screenshot 2021-07-30 at 12 05 41" src="https://user-images.githubusercontent.com/7916532/127644293-94c46341-4626-4f5d-bd5d-01b2ffe75202.png">

For multi search, make the "The Consumer ODS code X26 is not enabled for GP Connect" text slightly more prominent so its less easy to miss.  Currently the text blends with the rest of the details.

This could be something simple like putting a background yellow highlight on that portion of text?  Perhaps also separating on a newline?

**Comment by ChristopherJamesMorris** [comment]
This is now implemented and released in v1.4 of the Checker
