### ISSUE TITLE
User admin screen filter controls

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-appointment-checker#193]
Amend the admin screen filter controls so:

1. It's possible to filter on multi search status
2. It's possible to filter on access level
3. The filters are applied with one button - Apply filter - which applies all filters/searching at once (email, name, organisation, access level, status, multi search).

---

**Before:**

<img width="1356" alt="Screenshot 2021-07-30 at 12 21 33" src="https://user-images.githubusercontent.com/7916532/127645947-e4778c6c-7601-4587-98d0-02cf6f0bfabe.png">

---

**After:**

<img width="1356" alt="Screenshot 2021-07-30 at 12 26 51" src="https://user-images.githubusercontent.com/7916532/127646714-9407806d-3828-49d6-8698-4c26d6389aa4.png">

**Comment by ChristopherJamesMorris** [comment]
This is now implemented and released in v1.4 of the Checker
