### ISSUE TITLE
Organisation addresses are all in the first address line in the application.organisation table

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-appointment-checker#21]
addresses need splitting by line and putting into their relevant fields:

<img width="785" alt="Screenshot 2020-10-23 at 09 55 43" src="https://user-images.githubusercontent.com/7916532/96978134-ef680400-1515-11eb-9a9e-a496e35c1a98.png">

**Comment by ChristopherJamesMorris** [comment]
This is because Spine only has 'postal address' and 'postcode' - it doesn't split out the individual address components.

**Comment by jonnyry** [comment]
Split on comma (or other separator) - we need to check the separator in the INT environment.  I have a feeling it might be something else.

**Comment by ChristopherJamesMorris** [comment]
This issue has now been resolved and checked in to the repo.

**Comment by jonnyry** [comment]
Fix tested on UAT environment.
