### ISSUE TITLE
Black screen / NullReferenceException on search

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-appointment-checker#221]
*(Was tested using LDAP SDS)*

**Searching on X26 and X26 on DEV:**

<img width="252" alt="Screenshot 2021-11-19 at 10 31 52" src="https://user-images.githubusercontent.com/7916532/142608621-cbd054a7-df63-47ee-95dd-66893fae3879.png">

**Results in a blank screen:**

<img width="686" alt="Screenshot 2021-11-19 at 10 32 04" src="https://user-images.githubusercontent.com/7916532/142608791-9c55ba51-aa83-4572-b2ee-a68e0e7abb5b.png">

**NullReferenceException in the database:**

<img width="1882" alt="Screenshot 2021-11-19 at 10 32 45" src="https://user-images.githubusercontent.com/7916532/142608871-c626f0f3-56b6-46be-9b47-b337b1f7508c.png">

**Comment by jonnyry** [comment]
Fixed

**Comment by ChristopherJamesMorris** [comment]
Fixed.
