### ISSUE TITLE
Exception on search

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-appointment-checker#28]
Provider ODS code:  ABC
Consumer ODS code: DEF

results in the following error:

<img width="1378" alt="Unknown" src="https://user-images.githubusercontent.com/7916532/97023990-2954fc80-154e-11eb-8dd6-f0104cf8604e.png">

The issue is not logged to the database.

**Comment by ChristopherJamesMorris** [comment]
This issue has now been resolved and checked in to the repo.

**Comment by jonnyry** [comment]
Fix tested on UAT environment.
