### ISSUE TITLE
Backslash character in ODS code box results in a blank page

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-appointment-checker#29]

**Comment by ChristopherJamesMorris** [comment]
Jonny, can you give me a bit more insight. I put in a backslash but it just responded saying the code didn't exist.

**Comment by jonnyry** [comment]
Chris I've sent you a recording of the issue on Slack

**Comment by ChristopherJamesMorris** [comment]
This issue has now been resolved and checked in to the repo.

**Comment by jonnyry** [comment]
Still occuring on UAT.

**Comment by ChristopherJamesMorris** [comment]
I must've not checked in the fix - I've attached what I am getting when entering various combinations of codes.

![A20047 - B](https://user-images.githubusercontent.com/70885326/98351749-07ab4900-2015-11eb-8a54-a540f8f34045.png)
![A - B](https://user-images.githubusercontent.com/70885326/98351762-0c6ffd00-2015-11eb-9f79-4d0254f51ff7.png)
![A20047 - backslash](https://user-images.githubusercontent.com/70885326/98351858-2dd0e900-2015-11eb-8c53-17a3246daffd.png)
![backslash - A20047](https://user-images.githubusercontent.com/70885326/98351911-44774000-2015-11eb-9ee9-cd46cfe3b146.png)
![backslash - backslash](https://user-images.githubusercontent.com/70885326/98351969-5822a680-2015-11eb-9660-e3dbc28481df.png)
![forwardslash - forwardslash](https://user-images.githubusercontent.com/70885326/98352032-68d31c80-2015-11eb-8d01-063b66cda7ae.png)
