### ISSUE TITLE
Provider and Consumer labels may need clarification

### ISSUE THREAD

**Issue by petlove782** [nhsconnect/gpconnect-appointment-checker#36]
Raised by Rebecca Pierce

Users might not know what a provider or consumer is.

I would prefer to see it saying provider of appointments and organisation attempting the booking

**Comment by ChristopherJamesMorris** [comment]
I've checked in this change for review.

**Comment by petlove782** [comment]
thanks Chris, having looked at my issue wording above, we just need to make it clear that noone can book anything. we can discuss once i've reviewed the change

**Comment by KatherineBliss** [comment]
Leave as is for now, (provider and consumer) and ensure that help text explains these terms.
