### ISSUE TITLE
Sign in / Log out

### ISSUE THREAD

**Issue by KatherineBliss** [nhsconnect/gpconnect-appointment-checker#37]
Screens tell you you need to sign in, but log out. Can it be consistent please.

![logoff](https://user-images.githubusercontent.com/58551387/98552945-fb362300-2296-11eb-81fc-dc840a77bf63.JPG)

![signin](https://user-images.githubusercontent.com/58551387/98552975-04bf8b00-2297-11eb-8879-189ae08483a0.JPG)

**Comment by ChristopherJamesMorris** [comment]
Change logout to signout.

**Comment by ChristopherJamesMorris** [comment]
This is now resolved and will be available for checking in the next release to UAT.
