### ISSUE TITLE
Repeat the column headings in the results table for each branch surgery

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-appointment-checker#39]
(raised on the product development call) 

Suggest we have a separate table for each branch, with the branch name above the table headers, rather than below it.

**Comment by ChristopherJamesMorris** [comment]
TO make the header row fixed so it never disappears, in effect the table data is a "second table".

**Comment by KatherineBliss** [comment]
This suggestion/request has been superseded by accessibility improvements. There will be a separate table for each branch location. See the Accessibility requirements ticket.

**Comment by ChristopherJamesMorris** [comment]
Currently implementing #44 so will close this ticket.
