### ISSUE TITLE
Accessibility Statement

### ISSUE THREAD

**Issue by KatherineBliss** [nhsconnect/gpconnect-appointment-checker#53]
Create a page for an Accessibility page and add a link to it in the application footer.

Text is in attached file.

[Accessibility statement v0.1 Draft.docx](https://github.com/nhsconnect/gpconnect-appointment-checker/files/5601788/Accessibility.statement.v0.1.Draft.docx)

**Comment by ChristopherJamesMorris** [comment]
Fixed and tested. Now closing.
