### ISSUE TITLE
Help page for users

### ISSUE THREAD

**Issue by KatherineBliss** [nhsconnect/gpconnect-appointment-checker#54]
Create a page for Help text and add a link to it in the application footer.

Text is in the attached file.

[Appointment Checker Help Text v1.0.docx](https://github.com/nhsconnect/gpconnect-appointment-checker/files/5601802/Appointment.Checker.Help.Text.v1.0.docx)

**Comment by ChristopherJamesMorris** [comment]
Fixed and tested. Now closing.
