### ISSUE TITLE
Labels and alt text for screen readers

### ISSUE THREAD

**Issue by Mhitchins** [nhsconnect/gpconnect-appointment-checker#56]
If you open a screen reader (e.g. Windows Narrator Win+Ctrl+Enter) and tab between screen elements, you'll see that the narrated text could be more informative. Compare with https://www.nhs.uk/service-search/find-a-gp. For example, on Find a GP when you tab onto the data entry field it says 'Enter a town, city or postcode in England'. In the Appointment Checker ODS code entry fields, it should say something similarly helpful.

**Comment by ChristopherJamesMorris** [comment]
Currently under consideration as to what the input boxes should be labelled as.

**Comment by jonnyry** [comment]
As discussed.

<img width="582" alt="Screenshot 2020-12-02 at 16 51 46" src="https://user-images.githubusercontent.com/7916532/100904672-23442b00-34bf-11eb-9f7f-51de8160564d.png">

**Comment by ChristopherJamesMorris** [comment]
@Mhitchins Would you care to evaluate the changes we have made and if you are broadly in agreement, we shall close the ticket you raised.

Thank you.

**Comment by Mhitchins** [comment]
After a chat with Chris, I'm in agreement so this ticket can be closed.
