### ISSUE TITLE
JWT is not Base 64

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-appointment-checker#60]
Following issue returned when connecting to ODS code B82617 in the DEV environment:

```
{
  "resourceType": "OperationOutcome",
  "meta": {
    "profile": [
      "https://fhir.nhs.uk/STU3/StructureDefinition/GPConnect-OperationOutcome-1"
    ]
  },
  "issue": [
    {
      "severity": "error",
      "code": "invalid",
      "details": {
        "coding": [
          {
            "system": "https://fhir.nhs.uk/STU3/CodeSystem/Spine-ErrorOrWarningCode-1",
            "code": "BAD_REQUEST",
            "display": "BAD_REQUEST"
          }
        ]
      },
      "diagnostics": "JWT is not Base 64"
    }
  ]
}
```

If we speak to @SimonFarrowNHS he may be able to shine some light on this - this is returned from the B82617 demonstrator on Orange.  We don't however get the same issue when connecting to A20047 on Orange.

**Comment by SimonFarrowNHS** [comment]
Can we see the authorization header causing this please?
Could be due to the encoding not being base 64 url without padding.
eg If there are trailing = signs then that is not valid. Equally if vanilla base 64 encoding has been used rather than base64 url encoding then that will cause this response.

**Comment by ChristopherJamesMorris** [comment]
After speaking to @SimonFarrowNHS it transpires that there is an issue in the Demonstrator and there is a fix which will be released mid next week.

Quote "It was barfing on the url encoded character _ which replaces minus, so it is in fact expecting normal base 64 not url encoded 64"

When the fix is in place, we will need to rerun the same integration test.

**Comment by SimonFarrowNHS** [comment]
I have raised #353 for the bug fix.

**Comment by jonnyry** [comment]
This is now fixed and release to orange testlab.
