### ISSUE TITLE
"free slots found" label has wrong value

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-appointment-checker#63]
<img width="989" alt="Screenshot 2020-11-30 at 15 51 05" src="https://user-images.githubusercontent.com/7916532/100631878-1b03b880-3324-11eb-90d8-b68a175ee752.png">

**Comment by ChristopherJamesMorris** [comment]
Fixed and available in the next build.

**Comment by jonnyry** [comment]
Fixed and tested.
