### ISSUE TITLE
Add cookies banner

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-appointment-checker#77]
Add cookies banner like the nhs.uk one, though without the section on analytics cookies (since we don’t use analytics cookies).

Just a single button to dismiss the banner is sufficient. Dismissing the banner should be remembered so the next time you visit the site you don’t have to dismiss the banner again (unless you have cleared your cookies of course).

![3B0E2379-D5EF-4231-9A66-50FF505DC483](https://user-images.githubusercontent.com/7916532/100942686-b5662680-34f3-11eb-87b6-262a71489c9b.jpeg)

**Comment by ChristopherJamesMorris** [comment]
I've done the work but is it worth reviewing the text?

Cookies on the NHS website

We've put some small files called cookies on your device to make our site work.

Let us know if this is OK. We'll use a cookie to save your choice. You can read more about our cookies before you choose.

I'm OK with this

**Comment by jonnyry** [comment]
The cookies we use aren't optional so we need to amend the text slightly for now:

```
We've put some small files called cookies on your device to make our site work.  You can read more about our cookies.

[OK]
```

We'll get a formal review of this text done when we author the cookies policy.

**Comment by jonnyry** [comment]
Fixed and tested.
