### ISSUE TITLE
System.DllNotFoundException, Unable to load shared library 'ldap-2.4.so.2' or one of its dependencies. 

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-appointment-checker#82]
On login get the following:

{ "type": "System.Exception", "message": "An error was encountered while handling the remote login.", "stacktrace": "   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)\n   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)\n   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)\n   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)", "innerException": { "type": "System.DllNotFoundException", "message": "Unable to load shared library 'ldap-2.4.so.2' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libldap-2.4.so.2: cannot open shared object file: No such file or directory", "stacktrace": "   at gpconnect_appointment_checker.Startup.<>c.<AddAuthenticationServices>b__13_4(AuthenticationFailedContext context) in \/src\/gpconnect-appointment-checker\/Startup.cs:line 98\n   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectEvents.AuthenticationFailed(AuthenticationFailedContext context)\n   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.RunAuthenticationFailedEventAsync(OpenIdConnectMessage message, Exception exception)\n   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleRemoteAuthenticateAsync()\n   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()" } }

**Comment by ChristopherJamesMorris** [comment]
Jonny, 

You need to load additional libraries into the Linux environment for ldap4net to work:-

Refer the following: https://github.com/flamencist/ldap4net
