### ISSUE TITLE
LDAP attributes are showing as "System.String[]" is logging.spine_message_log

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-appointment-checker#85]
`ou=services, o=nhs (&(nhsIDCode=A20047)(objectClass=nhsMhs)(nhsMhsSvcIA=urn:nhs:names:services:gpconnect:fhir:rest:read:metadata-1)) System.String[]`

**Comment by ChristopherJamesMorris** [comment]
Fixed in the latest release.

**Comment by jonnyry** [comment]
Tested.
