### ISSUE TITLE
Display of address from from SDS - duplicate commas

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-appointment-checker#89]
Minor cosmetic:

When displaying the address to the user, e.g.:

`MAIN STREET SURGERY (X111111) - 1 BATEMAN STREET, , , LEEDS, YORKSHIRE LS1 1AA`

It would be nicer if this could read:

`MAIN STREET SURGERY (X111111) - 1 BATEMAN STREET, LEEDS, YORKSHIRE LS1 1AA`

I.e. any repeated adjoining commas could be removed

**Comment by ChristopherJamesMorris** [comment]
This is now fixed in the develop branch. Done as part of the fix to #92 as they were interconnected.

**Comment by jonnyry** [comment]
Doesn't appear to be working...

<img width="920" alt="Screenshot 2021-01-19 at 14 04 20" src="https://user-images.githubusercontent.com/7916532/105044954-3efb9480-5a5f-11eb-91be-823f28a78d1c.png">

**Comment by jonnyry** [comment]
Fixed
