### ISSUE TITLE
Nullreferenceexception when getting location

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-appointment-checker#92]
K83064

`{ "type": "**System.NullReferenceException**", "message": "Object reference not set to an instance of an object.", "stacktrace": "   at **gpconnect_appointment_checker.GPConnect.GpConnectQueryExecutionService.GetLocation**(String reference, List`1 scheduleResources, List`1 locationResources) in \/src\/gpconnect-appointment-checker.GPConnect\/SlotSearch.cs:line 146\n   at gpconnect_appointment_checker.GPConnect.GpConnectQueryExecutionService.<>c__DisplayClass13_0.<GetFreeSlots>b__7(<>f__AnonymousType0`2 <>h__TransparentIdentifier0) in \/src\/gpconnect-appointment-checker.GPConnect\/SlotSearch.cs:line 76\n   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)\n   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)\n   at System.Linq.Enumerable.WhereSelectListIterator`2.ToArray()\n   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)\n   at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()\n   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)\n   at gpconnect_appointment_checker.GPConnect.GpConnectQueryExecutionService.GetFreeSlots(RequestParameters requestParameters, DateTime startDate, DateTime endDate, String baseAddress) in \/src\/gpconnect-appointment-checker.GPConnect\/SlotSearch.cs:line 100\n   at gpconnect_appointment_checker.GPConnect.GpConnectQueryExecutionService.ExecuteFreeSlotSearch(RequestParameters requestParameters, DateTime startDate, DateTime endDate, String baseAddress) in \/src\/gpconnect-appointment-checker.GPConnect\/GPConnectQueryExecutionService.cs:line 42\n   at gpconnect_appointment_checker.Pages.SearchModel.PopulateSearchResults(Spine providerGpConnectDetails, Organisation providerOrganisationDetails, Spine consumerGpConnectDetails, Organisation consumerOrganisationDetails) in \/src\/gpconnect-appointment-checker\/Pages\/Private\/Search.cshtml.cs:line 135\n   at gpconnect_appointment_checker.Pages.SearchModel.GetSearchResults() in \/src\/gpconnect-appointment-checker\/Pages\/Private\/Search.cshtml.cs:line 104\n   at gpconnect_appointment_checker.Pages.SearchModel.OnPostSearchAsync() in \/src\/gpconnect-appointment-checker\/Pages\/Private\/Search.cshtml.cs:line 66\n   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory.GenericTaskHandlerMethod.Convert[T](Object taskAsObject)\n   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory.GenericTaskHandlerMethod.Execute(Object receiver, Object[] arguments)\n   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeHandlerMethodAsync()\n   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeNextPageFilterAsync()\n   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Rethrow(PageHandlerExecutedContext context)\n   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeInnerFilterAsync()\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\n   at gpconnect_appointment_checker.Configuration.RequestLoggingMiddleware.Invoke(HttpContext context, ILogService logService) in \/src\/gpconnect-appointment-checker\/Configuration\/Infrastructure\/Logging\/RequestLoggingMiddleware.cs:line 22\n   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)\n   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)" }`

**Comment by ChristopherJamesMorris** [comment]
This is now fixed in the develop branch

**Comment by jonnyry** [comment]
@ChristopherJamesMorris Where a location has no address (as part of the search for free slots call), could you print the following in italics where the address would have been:

_(no address provided)_

**Comment by jonnyry** [comment]
@ChristopherJamesMorris getting a nullreferenceexception now...

{ "type": "System.NullReferenceException", "message": "Object reference not set to an instance of an object.", "stacktrace": "   at gpconnect_appointment_checker.Helpers.StringExtensions.<>c.<AddressBuilder>b__3_0(String s) in \/src\/gpconnect-appointment-checker.Helpers\/StringExtensions.cs:line 36\n   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()\n   at System.String.Join(String separator, IEnumerable`1 values)\n   at gpconnect_appointment_checker.Helpers.StringExtensions.AddressBuilder(List`1 addressLines, String district, String city, String postalCode, String country) in \/src\/gpconnect-appointment-checker.Helpers\/StringExtensions.cs:line 36\n   at gpconnect_appointment_checker.Pages.Private.Pages_Private_SearchResults.ExecuteAsync() in \/src\/gpconnect-appointment-checker\/Pages\/Private\/SearchResults.cshtml:line 33\n   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)\n   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)\n   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)\n   at Microsoft.AspNetCore.Mvc.TagHelpers.PartialTagHelper.RenderPartialViewAsync(TextWriter writer, Object model, IView view)\n   at Microsoft.AspNetCore.Mvc.TagHelpers.PartialTagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)\n   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, Int32 i, Int32 count)\n   at gpconnect_appointment_checker.Pages.Private.Pages_Private_Search.<ExecuteAsync>b__15_0() in \/src\/gpconnect-appointment-checker\/Pages\/Private\/Search.cshtml:line 7\n   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.GetChildContentAsync(Boolean useCachedResult, HtmlEncoder encoder)\n   at Microsoft.AspNetCore.Mvc.TagHelpers.RenderAtEndOfFormTagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)\n   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, Int32 i, Int32 count)\n   at gpconnect_appointment_checker.Pages.Private.Pages_Private_Search.ExecuteAsync()\n   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)\n   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)\n   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)\n   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)\n   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()\n--- End of stack trace from previous location ---\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\n   at gpconnect_appointment_checker.Configuration.RequestLoggingMiddleware.Invoke(HttpContext context, ILogService logService) in \/src\/gpconnect-appointment-checker\/Configuration\/Infrastructure\/Logging\/RequestLoggingMiddleware.cs:line 22\n   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)\n   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)\n   at gpconnect_appointment_checker.Configuration.Infrastructure.ApplicationBuilderExtensions.<>c.<<ConfigureApplicationBuilderServices>b__0_0>d.MoveNext() in \/src\/gpconnect-appointment-checker\/Configuration\/Infrastructure\/ApplicationBuilderExtensions.cs:line 37\n--- End of stack trace from previous location ---\n   at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)\n   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)" }

**Comment by jonnyry** [comment]
Fixed
