### ISSUE TITLE
Putting a space at the end of an ODS code cause the LDAP query to fail

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-appointment-checker#94]
Enter an ODS code with a space at the end, e.g. `A20047 ` in either the provider or consumer ODS code field causes the LDAP portion of the search to fail, with the following error:

`EXCEPTION: LdapLocalException: Invalid value in escape sequence " " (87) Filter Error`

Could we perform a trim() on the contents of both boxes so this doesn't happen?

It's quite easy to put a trailing space in the box when copying and pasting ODS codes from somewhere.

**Comment by ChristopherJamesMorris** [comment]
This is committed into the latest build.

**Comment by jonnyry** [comment]
Where there's whitespace at the start or the end of either of the ODS codes, can you just trim it, instead of it causing an error?

**Comment by jonnyry** [comment]
@ChristopherJamesMorris could the ODS code in the search box be returned trimmed (leading and trailing) in the response?
Also could the ODS code be upper cased?

**Comment by jonnyry** [comment]
Fixed
