### ISSUE TITLE
Set user idle session timeout to 30 mins

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-appointment-checker#95]

**Comment by ChristopherJamesMorris** [comment]
This change has been implemented and is now contained in a pull request.

**Comment by jonnyry** [comment]
@ChristopherJamesMorris is this configurable? looking for a way to test (without waiting 30 mins)

**Comment by jonnyry** [comment]
@ChristopherJamesMorris Temporarily set to 1 minute to test and released to dev.appointmentchecker, though haven't observed it working, could you take a look?

https://github.com/nhsconnect/gpconnect-appointment-checker/commit/8ee6cd9fbecc43ba66875eddb2a285ac34df01d9

**Comment by jonnyry** [comment]
Fixed.
