### ISSUE TITLE
Ensure HSTS / Strict Transport Security headers are returned

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-appointment-checker#96]

**Comment by ChristopherJamesMorris** [comment]
This change has been implemented and is now contained in a pull request.

**Comment by jonnyry** [comment]
The header doesn't appear to be visible, further investigation required

https://stackoverflow.com/questions/51906676/enabling-hsts-in-aws-elb-application-load-balacer
https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-5.0&tabs=visual-studio

**Comment by jonnyry** [comment]
Fixed.
