### ISSUE TITLE
Implement HTML directives no-cache

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-appointment-checker#99]
Is it possible to apply no-cache on all pages except for images?

**Comment by ChristopherJamesMorris** [comment]
This change has been implemented and is now contained in a pull request.

**Comment by jonnyry** [comment]
@ChristopherJamesMorris All pages (except for the search page itself) are using the following for cache-control which allows caching to happen (despite the name!):

`cache-control: public, no-cache`

The PEN testers advise we use

`cache-control: no-store` and `Pragma: no-cache` instead which do prevent caching.

**Comment by jonnyry** [comment]
@ChristopherJamesMorris  Can you also add `Pragma: no-cache`?

**Comment by jonnyry** [comment]
Fixed.
